# Generated by Django 2.2.1 on 2019-05-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='adddress',
            new_name='address',
        ),
    ]
